### ISSUE TITLE
8/26 TODO

### ISSUE THREAD

**Issue by SeolJaeHyeok** [goorm-hackathon/Jumping-Frog-Client#17]
- [x] JUMP 로고 로딩 속도 너무 빠르게 넘어감? (2초?)
- [x] 시작하기 => 구독하기
- [ ] 모달 창 크기 조정
- [ ] 질문 내용 추가
- [x] 이름 validation 한글만 입력 가능하게
- [x] 직업 항목 삭제: 장기코디네이터, 천문학자, ui 디자이너, 의무기록사,
- [x] 2번째 모달에 [name]값 안뜸
