### ISSUE TITLE
08/25 TODO List

### ISSUE THREAD

**Issue by SeolJaeHyeok** [goorm-hackathon/Jumping-Frog-Client#5]
- [x] Survey Page UI 마무리
- [x] End Page 마무리
- [x] Progress Bar 구현
- [x] Survey Page 데이터 전역 관리
- [x] 뒤로 갔을 때 데이터 유지
- [x] 전역으로 관리된 데이터 POST 요청
- [ ] 스타일 디테일 수정
- [x] Node Mailer에서 사용할 HTML 파일 만들기
- [x]   Header Logo로 변경하기
- [x] Not Found Page

++
1. End Page에서 어디로 이동할 것인지?
